prepdwi_dir: /path/to/prepdwi/folder
fmriprep_dir: /path/to/fmriprep/folder

participants_tsv: participants.tsv



#use prepdwi singularity container for mrtrix3
singularity: /project/6007967/akhanf/singularity/bids-apps/khanlab_prepdwi_latest.sif

#for grabbing data from prepdwi
entities:
  datatype: dwi
  space: T1w
  suffix: preproc

#mrtrix tracking, tracts (in millions)
ntracts_million: 10


